### ISSUE TITLE
can't modify middleware stack after making a request 

### ISSUE THREAD

**Issue by nathanleclaire** [honeycombio/beeline-ruby#15] opened 2019-04-08 18:20 UTC
A user is reporting seeing this issue trying to use the Ruby Beeline.

**Comment by nathanleclaire** [comment] 2019-04-08 18:24
Seems to work fine for `GET` requests, problem might be with other methods.

**Comment by rhymes** [comment] 2019-05-04 17:18
@nathanleclaire 

AFAIK the issue is due to how https://github.com/honeycombio/faraday-honeycomb interacts with Faraday.

The beeline installs it's "monkeypatch" for Faraday but that doesn't work with its recent versions (of Faraday) resulting in the aforamentioned error.

Basically the adapter call always has to be the last one made when configuring the Faraday client, but if this faraday-honeycomb autoinstalls itself before other middleware are added, then you get that error. Because of line 34 here:

https://github.com/honeycombio/faraday-honeycomb/blob/70917d213b0af57c6c2360ad19c3477b54f29130/lib/faraday-honeycomb/auto_install.rb#L30-L35

As you can see it calls the default adapter, but if any other gem has already installed an adapter, then Faraday explodes. See

https://github.com/lostisland/faraday/blob/ffc6911ed345021259062fe6d789d63c195dfd53/lib/faraday/rack_builder.rb#L156-L168

We've noticed this error, see https://github.com/thepracticaldev/dev.to/issues/2357#issuecomment-481670162, with a Gemfile with both [octokit](https://rubygems.org/gems/octokit) (which does not pass a block to Faraday's initializer, hence ending up in the `else` part) and beeline-ruby

Hope this helps. I'd consider two changes: the extensions are optional, or least can be deactivated. Right now there's no way to not load any of the instrumentations when the gem is required, see https://github.com/honeycombio/beeline-ruby/blob/master/lib/honeycomb/instrumentations.rb

The second proposal is to remove the call to `Faraday.default_adapter` here https://github.com/honeycombio/faraday-honeycomb/blob/70917d213b0af57c6c2360ad19c3477b54f29130/lib/faraday-honeycomb/auto_install.rb#L34 - Faraday can be used with many different adapters and because of how it works, the call to the adapter's choice has to be the last one but in a Gemfile there's no easy way to make sure that `beeline-ruby` is the last in the sequence of gems loaded.

Hope this helps

**Comment by joho** [comment] 2019-05-13 00:02
I'm also experiencing this issue. Getting `Faraday::RackBuilder::StackLocked (can't modify middleware stack after making a request)` when using the octokit gem.

**Comment by martin308** [comment] 2019-05-14 18:28
@rhymes @joho I've made a stab at fixing this issue over here https://github.com/honeycombio/faraday-honeycomb/pull/7, can you let me know what you think and if it fixes the specific issues you are seeing?

**Comment by martin308** [comment] 2019-05-17 23:44
@rhymes @joho I've merged a PR now by @BRMatt which should fix this, it's been released in v0.3.2 of the faraday integration!

**Closed by martin308** 2019-05-17 23:44 UTC

**Comment by rhymes** [comment] 2019-05-18 11:35
Thanks @martin308 it seems to be working, I can't reproduce the error! I wonder if you should bump the required version of `faraday-honeycomb` in this gem as well
